server:
  port: 8001
#  servlet:
#    context-path: /api/v1
spring:
  data:
    mongodb:
      host: 8.137.20.123
      port: 27017
      username: levi
      password: li199523
      database: pro_dbserver

  compression:
    #是否对响应数据开启gzip压缩,默认false
    enabled: true
    #响应内容长度超过设置大小时进行压缩,默认值为2048(2KB,不带单位时默认为字节)
    min-response-size: 1024KB
    #对指定的响应类型进行压缩,值是数组,用逗号隔开
    mime-types: text/javascript

#visual:
#  flow:
#    apiPrefix: /api/v1
##    enableDefaultApi: true
##    compileScriptApiPath: /compile-script
##    listWorkflowsApiPath: /engine/workflowList
#    resourcePrefix: /api/v1