server:
  port: 8001
#  servlet:
#    context-path: /api/v1
spring:
  data:
    mongodb:
      host: 8.137.20.123
      port: 27017
      username: levi
      password: li199523
      database: pro_dbserver


#visual:
#  flow:
#    apiPrefix: /api/v1
##    enableDefaultApi: true
##    compileScriptApiPath: /compile-script
##    listWorkflowsApiPath: /engine/workflowList
#    resourcePrefix: /api/v1